package Frontend;

import Account.Account;
import Account.AccountType;
import Person.Customer.Customer;
import Utils.Helpers;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class CustomerDetailView extends AbstractJPanel {
    private JButton backButton;
    private JPanel basePanel;
    private JTabbedPane tabbedPane1;
    private JPanel savingsAccountPanel;
    private JPanel checkingAccountPanel;
    private JPanel loanAccountPanel;
    private Customer customer;

    public CustomerDetailView(Customer customer) {
        this.customer = customer;
        savingsAccountPanel.setLayout(new BorderLayout());
        checkingAccountPanel.setLayout(new BorderLayout());
        loanAccountPanel.setLayout(new BorderLayout());

        refresh();
        backButton.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Frontend.getInstance().back();
            }
        });
    }

    public void refresh(){
        Account savingsAcc = Helpers.getAccount(AccountType.SAVING, customer.getAccounts());
        if(savingsAcc != null){
            savingsAccountPanel.removeAll();
            savingsAccountPanel.add(ViewFactory.getAccount(this.customer, AccountType.SAVING, savingsAcc, true, false).getBasePanel());
        }

        Account checkingAcc = Helpers.getAccount(AccountType.CHECKING, customer.getAccounts());
        if(checkingAcc != null){
            checkingAccountPanel.removeAll();
            checkingAccountPanel.add(ViewFactory.getAccount(this.customer, AccountType.CHECKING, checkingAcc, true, false).getBasePanel());
        }
        loanAccountPanel.add(ViewFactory.getLoansView(true, this.customer, true).getBasePanel());
    }


    @Override
    public JPanel getBasePanel() {
        return basePanel;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        basePanel = new JPanel();
        basePanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(2, 3, new Insets(0, 0, 0, 0), -1, -1));
        backButton = new JButton();
        backButton.setText("Back");
        basePanel.add(backButton, new com.intellij.uiDesigner.core.GridConstraints(0, 2, 1, 1, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_FIXED, null, null, null, 0, false));
        final com.intellij.uiDesigner.core.Spacer spacer1 = new com.intellij.uiDesigner.core.Spacer();
        basePanel.add(spacer1, new com.intellij.uiDesigner.core.GridConstraints(0, 0, 1, 2, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_HORIZONTAL, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_WANT_GROW, 1, null, null, null, 0, false));
        tabbedPane1 = new JTabbedPane();
        basePanel.add(tabbedPane1, new com.intellij.uiDesigner.core.GridConstraints(1, 0, 1, 3, com.intellij.uiDesigner.core.GridConstraints.ANCHOR_CENTER, com.intellij.uiDesigner.core.GridConstraints.FILL_BOTH, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_SHRINK | com.intellij.uiDesigner.core.GridConstraints.SIZEPOLICY_CAN_GROW, null, new Dimension(200, 200), null, 0, false));
        savingsAccountPanel = new JPanel();
        savingsAccountPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("Savings", savingsAccountPanel);
        checkingAccountPanel = new JPanel();
        checkingAccountPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("Checking", checkingAccountPanel);
        loanAccountPanel = new JPanel();
        loanAccountPanel.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
        tabbedPane1.addTab("Loans", loanAccountPanel);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return basePanel;
    }
}
